apiVersion: v1
kind: Pod
metadata:
  name: pod-env-var
  labels:
    name: pod-env-var
spec:
  containers:
  - name: pod-env-configmap
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
     - configMapRef:
        name: demo-configmap