apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
  - name: hostpath-container
    image: nginx:latest
    volumeMounts:
    - name: hostpath-volume
      mountPath: /usr/share/nginx/html  # Mount the volume to this path in the container
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp/hostpath-data  # Path on the host machine
      type: DirectoryOrCreate  # Create the directory if it doesn't exist
