apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: vijayvct/myapp:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
