apiVersion: v1
kind: Service
metadata:
 name: nginx-loadbalancer
spec:
 type: LoadBalancer
 selector:
    app: nginx-app
 ports:
  - name: "http"
    port: 80 #Loadbalancer Port
    targetPort: 80 #Container Port
    
  - name: "https"
    port: 443
    targetPort: 443